### ISSUE TITLE
Tool crashes when input file extension is not `.txt`

### ISSUE THREAD

**Issue by SerpentBytes** [Myrfion/izyum#2]
## Environment Information

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

The tool crashes when the `-i` option is used and the source file supplied is not in `.txt` format

See below:

```
[Error: ENOTDIR: not a directory, scandir '/Users/taimoordawami/Desktop/Silver Blaze.log'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: '/Desktop/Silver Blaze.log'
}

```

**Comment by Myrfion** [comment]
fix in #8
